// flow-typed signature: a2ec283515d36a5420555282dd0d96b4
// flow-typed version: <<STUB>>/reset-css_v^3.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reset-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reset-css' {
  declare module.exports: any;
}
